import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

import { getServerSession } from "next-auth/next";
import { options } from "../app/api/auth/[...nextauth]/options";
import Session from "../components/session";

import Nav from "@/components/nav";
import { SidePanel } from "@/components/sidePanel";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session session={session}>
          <Nav />
          <SidePanel>{children}</SidePanel>
        </Session>
      </body>
    </html>
  );
}
